port:  5000
markdown: kramdown
name: 
url: http://findmyreps.datamade.us
encoding: utf-8
timezone: America/Chicago
description: 
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyBlYSeJ85rkjyaMgy0Fju6Wrii7mJXanog
